### ISSUE TITLE
Error output from freebox_

### ISSUE THREAD

**Issue by Owned67** [architek/myfiles#1]
Bonjour,

désoler de poster ici mais impossible d'ouvrir un ticket sur ton fork....

comment corriger cette erreur s'il te plaît :

2017/11/12-02:15:10 [700] Error output from freebox_:
2017/11/12-02:15:10 [700] Must be called freebox_{temp|bandwidth|freeplug|snr|fec|attn|switch1|switch2|switch3|switch4|uptime|multi}.
2017/11/12-02:15:10 [700] Service 'freebox_' exited with status 255/0.
2017/11/12-02:15:10 [700] Error output from freebox_:
2017/11/12-02:15:10 [700] Must be called freebox_{temp|bandwidth|freeplug|snr|fec|attn|switch1|switch2|switch3|switch4|uptime|multi}.
2017/11/12-02:15:10 [700] Service 'freebox_' exited with status 255/0.
2017/11/12-02:16:52 Server closing`

Les graphiques fonctionnent bien, c'est juste que ça me spam dans le log....
Merci

**Comment by architek** [comment]
Bonjour,

Désolé je n'avais pas vu ton message. Tu l'as résolu? 
Il y avait une erreur dans la doc, il faut nommer le lien freebox_multi (et non freebox_) pour activer le mode multi.
Je vais ouvrir les ticket pour le plugin. 
Merci
